services:
  postgres:
    image: postgres:15
    container_name: evolution-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: evolution-redis
    restart: unless-stopped

    command: redis-server --appendonly yes

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  evolution-go:
    image: evoapicloud/evolution-go:0.7.2
    container_name: evolution-go

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    ports:
      - "8081:8081"
    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      SERVER_PORT: 8081

      CLIENT_NAME: evolution

      GLOBAL_API_KEY: ${GLOBAL_API_KEY}

      POSTGRES_AUTH_DB: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/evogo_auth?sslmode=disable
      POSTGRES_USERS_DB: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/evogo_users?sslmode=disable

      REDIS_ADDR: redis:6379

      DATABASE_SAVE_MESSAGES: "false"

      WADEBUG: INFO
      LOGTYPE: console

volumes:
  postgres_data:
  redis_data: